### ISSUE TITLE
login.starkandwayne.com ?

### ISSUE THREAD

**Issue by larspetrus** [starkandwayne/uaa-deployment-cf#2]
I tried this, and it failed on `quaa up --route login.starkandwayne.com` with a "The route is invalid: host format" message.

I assume/guess I should replace `login.starkandwayne.com` with a route that works for me, but I don't know what that would be.

**Comment by drnic** [comment]
@larspetrus your route would be something valid for your cloudfoundry. Run `cf domains` to see the available domains (our CF has `starkandwayne.com` as a domain), and then you're picking a route that is a subdomain (e.g. `login.starkandwayne.com` is a subdomain of `starkandwayne.com`; and I know we have a DNS `*.starkandwayne.com` wildcard and/or `login.starkandwayne.com` explicitly setup to point to our CF).

Learn more about CF routes + domains at https://docs.cloudfoundry.org/devguide/deploy-apps/routes-domains.html

**Comment by drnic** [comment]
Please reopen if you have more questions.
